spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-myj266u1.sql.tencentcdb.com:22094/micode_db?useSSL=false
    username: root
    password: anEii020827.
  redis:
    database: 0
    host: redis-10023.c290.ap-northeast-1-2.ec2.redns.redis-cloud.com
    port: 10023
    timeout: 5000
    username: default
    password: RUJJVrnJ5Pj7YSNBFCvvh78BaL7GrUX1
  rabbitmq:
    host: 8.219.222.88
    port: 5672
    password: guest
    username: guest
# 代码沙箱配置
codesandbox:
  type: remote
